// Generated by Dagger (https://google.github.io/dagger).
package com.example.app.ui.main.webview;

import androidx.fragment.app.Fragment;
import com.example.app.SessionManager;
import com.example.app.base.BaseFragment_MembersInjector;
import com.example.app.di.ViewModelProviderFactory;
import dagger.MembersInjector;
import dagger.android.DispatchingAndroidInjector;
import dagger.android.support.DaggerFragment_MembersInjector;
import javax.inject.Provider;

public final class WebviewFragment_MembersInjector implements MembersInjector<WebviewFragment> {
  private final Provider<DispatchingAndroidInjector<Fragment>> childFragmentInjectorProvider;

  private final Provider<SessionManager> sessionManagerProvider;

  private final Provider<ViewModelProviderFactory> providerFactoryProvider;

  public WebviewFragment_MembersInjector(
      Provider<DispatchingAndroidInjector<Fragment>> childFragmentInjectorProvider,
      Provider<SessionManager> sessionManagerProvider,
      Provider<ViewModelProviderFactory> providerFactoryProvider) {
    this.childFragmentInjectorProvider = childFragmentInjectorProvider;
    this.sessionManagerProvider = sessionManagerProvider;
    this.providerFactoryProvider = providerFactoryProvider;
  }

  public static MembersInjector<WebviewFragment> create(
      Provider<DispatchingAndroidInjector<Fragment>> childFragmentInjectorProvider,
      Provider<SessionManager> sessionManagerProvider,
      Provider<ViewModelProviderFactory> providerFactoryProvider) {
    return new WebviewFragment_MembersInjector(
        childFragmentInjectorProvider, sessionManagerProvider, providerFactoryProvider);
  }

  @Override
  public void injectMembers(WebviewFragment instance) {
    DaggerFragment_MembersInjector.injectChildFragmentInjector(
        instance, childFragmentInjectorProvider.get());
    BaseFragment_MembersInjector.injectSessionManager(instance, sessionManagerProvider.get());
    injectProviderFactory(instance, providerFactoryProvider.get());
  }

  public static void injectProviderFactory(
      WebviewFragment instance, ViewModelProviderFactory providerFactory) {
    instance.providerFactory = providerFactory;
  }
}
