// Generated by Dagger (https://google.github.io/dagger).
package com.example.app.ui.main.webview;

import dagger.internal.Factory;

public final class WebviewViewModel_Factory implements Factory<WebviewViewModel> {
  private static final WebviewViewModel_Factory INSTANCE = new WebviewViewModel_Factory();

  @Override
  public WebviewViewModel get() {
    return new WebviewViewModel();
  }

  public static WebviewViewModel_Factory create() {
    return INSTANCE;
  }

  public static WebviewViewModel newInstance() {
    return new WebviewViewModel();
  }
}
